name: deploy Highlight.js themes preview

on:
  push:
    branches:
      - main
    paths:
      - 'packages/spindle-highlightjs-themes/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/spindle-highlightjs-themes/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn build:example
      - name: deploy to live channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          entryPoint: ./packages/spindle-syntax-themes/
          channelId: live
