name: deploy Hooks preview

on:
  pull_request:
    paths:
      - 'packages/spindle-hooks/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/spindle-hooks/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn storybook:build
      - name: deploy to preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 30d
          entryPoint: ./packages/spindle-hooks/
