name: deploy UI preview

on:
  pull_request:
    # paths:
    #   - 'packages/spindle-ui/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: npx lerna bootstrap -- --frozen-lockfile
      - run: |
          yarn lerna run --scope @openameba/spindle-hooks build
          yarn lerna run --scope @openameba/spindle-ui storybook:build
      - name: deploy to preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          entryPoint: ./packages/spindle-ui/
