name: lint commit message(s)

on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Tokyo

jobs:
  lint-commit-message:
    name: lint commit message(s)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-v2
      - run: yarn install --frozen-lockfile
      - run: >
          npx commitlint
          --from "$(git merge-base "origin/${GITHUB_BASE_REF}" "origin/${GITHUB_HEAD_REF}")"
          --to "origin/${GITHUB_HEAD_REF}"
          --verbose
