name: publishing

on:
  push:
    tags:
      - '@openameba/*'

jobs:
  publish:
    name: publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Log in to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
      - name: Publishing with lerna
        run: npx lerna publish from-git
      - name: Hosting UI catalog when Spindle UI has been updated
        run: |
          if npx lerna changed | grep @openameba/spindle-ui; then
            npx lerna run --scope @openameba/spindle-ui storybook:build
            npx lerna run --scope @openameba/spindle-ui storybook:deploy -- --token $FIREBASE_TOKEN
          fi
