name: versioning

on:
  push:
    branches:
      - version/major
      - version/minor
      - version/patch
      - version/premajor
      - version/preminor
      - version/prepatch
      - version/prerelease

jobs:
  version:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Set git user
        run: |
          git config --global user.email "<>"
          git config --global user.name "openameba"
      - name: Extract version from branch name
        run: echo "::set-output name=version::$(echo ${GITHUB_REF##*/})"
        id: extract_version
      - name: Versioning with lerna
        # also see some options in lerna.json
        run: npx lerna version ${{ steps.extract_version.outputs.version }} --conventional-commits --create-release github --yes --no-private
        env:
          GH_TOKEN: ${{ github.token }}
